//! Size and sanity guard for the generated `llms.txt` LLM reference.
//!
//! `llms.txt` is regenerated by `scripts/generate-llms-txt.sh` (splicing
//! `docs/llms-txt-template.md` with a live `(render-llms-index)` dump — see
//! `lib/97-doc-renderer.lisp`) and checked into the repo root and
//! `docs/llms.txt`. This test does not regenerate it (that needs a release
//! build of the interpreter); it just pins the checked-in file against
//! silent bloat and template-splice mistakes so a future edit that balloons
//! the file, or forgets to run the generator, fails CI instead of shipping.

use std::fs;

const MAX_BYTES: u64 = 100_000;

#[test]
fn llms_txt_exists_and_stays_under_size_budget() {
    let meta = fs::metadata("llms.txt").expect("llms.txt must exist at the repo root");
    assert!(
        meta.len() < MAX_BYTES,
        "llms.txt is {} bytes, over the {MAX_BYTES}-byte budget -- see scripts/generate-llms-txt.sh",
        meta.len()
    );
    assert!(meta.len() > 1_000, "llms.txt looks truncated/empty");
}

#[test]
fn llms_txt_and_docs_copy_agree() {
    let root = fs::read_to_string("llms.txt").expect("llms.txt must exist at the repo root");
    let docs_copy =
        fs::read_to_string("docs/llms.txt").expect("docs/llms.txt must exist (Pages copy)");
    assert_eq!(
        root, docs_copy,
        "llms.txt and docs/llms.txt have drifted -- re-run scripts/generate-llms-txt.sh"
    );
}

#[test]
fn llms_txt_has_no_unspliced_template_markers() {
    let content = fs::read_to_string("llms.txt").unwrap();
    assert!(
        !content.contains("{{MODULE_TABLE}}") && !content.contains("{{FUNCTION_INDEX}}"),
        "llms.txt still contains an unspliced docs/llms-txt-template.md marker"
    );
}

#[test]
fn llms_txt_covers_the_expected_sections() {
    let content = fs::read_to_string("llms.txt").unwrap();
    for marker in [
        "Lamedh (ל)",
        "## 1. Syntax & semantic gotchas",
        "## 2. Module map",
        "## 3. Function index",
        "## 4. Worked examples",
        "defrecord",
        "defprotocol",
        "--mcp",
    ] {
        assert!(
            content.contains(marker),
            "llms.txt is missing expected content: {marker:?}"
        );
    }
}
