; 087_float_print_bits — issue #551: the shortest round-trip float
; printer (floats.asm float_print) checked on raw bit patterns, so the
; reader's own number parsing is out of the loop. Covers the edge cases
; of free-format printing (the unequal gap below a power of two, the
; smallest and largest normals and denormals, round-half-even
; boundaries, 0.1-style non-terminating fractions) plus a fixed
; xorshift64 stream of pseudo-random doubles. The expected file is
; generated by the same sequence through rustc's f64::to_string with
; ".0" appended to integral text, i.e. the reference printer.

%include "src/tags.inc"

extern make_float
extern print_value
extern print_newline

section .rodata
special:
    dq 0x0000000000000001, 0x0000000000000002, 0x000FFFFFFFFFFFFF
    dq 0x0010000000000000, 0x0010000000000001, 0x3FF0000000000000
    dq 0x3FF0000000000001, 0x3FEFFFFFFFFFFFFF, 0x3FB999999999999A
    dq 0x3FD3333333333333, 0x4340000000000000, 0x433FFFFFFFFFFFFF
    dq 0x43E0000000000000, 0x7FEFFFFFFFFFFFFF, 0x7FE0000000000000
    dq 0x4415AF1D78B58C40, 0x3E7AD7F29ABCAF48, 0x0000000000000000
    dq 0x8000000000000000, 0xBFF8000000000000, 0x8000000000000001
special_n equ ($ - special) / 8

section .text
global lamedh_main
lamedh_main:
    push r12
    push r13
    push r14
    lea r12, [rel special]
    mov r13, special_n
.special:
    mov rax, [r12]
    call emit
    add r12, 8
    dec r13
    jnz .special

    mov r12, 0x9E3779B97F4A7C15         ; xorshift64 state
    mov r13, 600
.rand:
    mov rax, r12                        ; x ^= x << 13; x ^= x >> 7; x ^= x << 17
    shl rax, 13
    xor r12, rax
    mov rax, r12
    shr rax, 7
    xor r12, rax
    mov rax, r12
    shl rax, 17
    xor r12, rax
    mov rax, r12
    mov rcx, rax
    shr rcx, 52
    and ecx, 0x7FF
    cmp ecx, 0x7FF
    jne .keep
    btr rax, 62                         ; never inf/NaN: clear the top exponent bit
.keep:
    call emit
    dec r13
    jnz .rand
    xor eax, eax
    pop r14
    pop r13
    pop r12
    ret

; emit(rax=f64 bits): PRINT the float, then a newline
emit:
    movq xmm0, rax
    call make_float
    mov rdi, rax
    call print_value
    call print_newline
    ret
