;;; Documentation Renderer
;;; Generates Markdown documentation from the help database
;;; Usage: (render-markdown-docs "path/to/docs/")

;;; Note: This requires file writing capability which Lamedh doesn't have.
;;; For now, this outputs to stdout and can be redirected.

(defun render-markdown-header (title level)
  "Output a markdown header."
  (let ((prefix (cond ((= level 1) "# ")
                      ((= level 2) "## ")
                      ((= level 3) "### ")
                      ((= level 4) "#### ")
                      (t "##### "))))
    (progn
      (princ prefix)
      (princ title)
      (terpri)
      (terpri))))

(defun render-markdown-code (code)
  "Output code in markdown format."
  (princ "```lisp")
  (terpri)
  (prin1 code)
  (terpri)
  (princ "```")
  (terpri))

(defun render-doc-entry-md (entry)
  "Render a single documentation entry as markdown."
  (let ((name (doc-get entry 'NAME))
        (type (doc-get entry 'TYPE))
        (syntax (doc-get entry 'SYNTAX))
        (desc (doc-get entry 'DESCRIPTION))
        (args (doc-get entry 'ARGS))
        (returns (doc-get entry 'RETURNS))
        (examples (doc-get entry 'EXAMPLES))
        (see-also (doc-get entry 'SEE-ALSO)))
    (progn
      ;; Header - print directly to avoid string issues
      (princ "### ")
      (princ name)
      (terpri)
      (terpri)
      ;; Type badge
      (princ "**Type:** `")
      (princ type)
      (princ "`")
      (terpri)
      (terpri)
      ;; Syntax
      (if syntax
          (progn
            (princ "**Syntax:** `")
            (princ syntax)
            (princ "`")
            (terpri)
            (terpri))
          nil)
      ;; Description
      (if desc
          (progn
            (princ desc)
            (terpri)
            (terpri))
          nil)
      ;; Arguments
      (if args
          (progn
            (princ "**Arguments:**")
            (terpri)
            (mapcar (lambda (arg)
                      (princ "- `")
                      (princ (car arg))
                      (princ "` - ")
                      (princ (cadr arg))
                      (terpri))
                    args)
            (terpri))
          nil)
      ;; Returns
      (if returns
          (progn
            (princ "**Returns:** ")
            (princ returns)
            (terpri)
            (terpri))
          nil)
      ;; Examples
      (if examples
          (progn
            (princ "**Examples:**")
            (terpri)
            (princ "```lisp")
            (terpri)
            (mapcar (lambda (ex)
                      (prin1 (car ex))
                      (princ "  ; => ")
                      (prin1 (cadr ex))
                      (terpri))
                    examples)
            (princ "```")
            (terpri)
            (terpri))
          nil)
      ;; See also
      (if see-also
          (progn
            (princ "**See also:** ")
            (princ (car see-also))
            (mapcar (lambda (s)
                      (princ ", ")
                      (princ s))
                    (cdr see-also))
            (terpri)
            (terpri))
          nil)
      ;; Separator
      (princ "---")
      (terpri)
      (terpri))))

;; PRINC-TO-STRING is now a kernel builtin (issue #150), backed by the printer;
;; the crude Lisp shim that used to live here has been removed.

(defun render-category-md (cat-name)
  "Render all docs in a category as markdown."
  (let ((cat (assoc cat-name HELP-CATEGORIES)))
    (if cat
        (progn
          ;; Print header manually to avoid string conversion issues
          (princ "# ")
          (princ cat-name)
          (princ " Functions")
          (terpri)
          (terpri)
          (princ (cadr cat))
          (terpri)
          (terpri)
          (princ "---")
          (terpri)
          (terpri)
          (mapcar (lambda (sym)
                    (let ((entry (get-doc sym)))
                      (if entry
                          (render-doc-entry-md entry)
                          nil)))
                  (caddr cat)))
        nil)))

(defun render-all-docs-md ()
  "Render all documentation categories to markdown (to stdout)."
  (render-markdown-header "Lamedh Reference Manual" 1)
  (princ "Auto-generated from Lisp documentation database.")
  (terpri)
  (terpri)
  (princ "---")
  (terpri)
  (terpri)
  ;; Table of contents
  (render-markdown-header "Categories" 2)
  (mapcar (lambda (cat)
            (princ "- ")
            (princ (car cat))
            (princ " - ")
            (princ (cadr cat))
            (terpri))
          (list-categories))
  (terpri)
  (princ "---")
  (terpri)
  (terpri)
  ;; Each category
  (mapcar (lambda (cat)
            (render-category-md (car cat)))
          (list-categories))
  (princ "---")
  (terpri)
  (princ "*Generated by Lamedh documentation system*")
  (terpri))

(defun render-function-index-md ()
  "Render alphabetical function index."
  (render-markdown-header "Function Index" 1)
  (terpri)
  (princ "| Function | Type | Category |")
  (terpri)
  (princ "|----------|------|----------|")
  (terpri)
  (mapcar (lambda (name)
            (let ((entry (get-doc name)))
              (progn
                (princ "| `")
                (princ name)
                (princ "` | ")
                (princ (doc-get entry 'TYPE))
                (princ " | ")
                (princ (doc-get entry 'CATEGORY))
                (princ " |")
                (terpri))))
          (sort (keys HELP-DB)
                (lambda (a b)
                  (string-lessp (prin1-to-string a)
                                (prin1-to-string b))))))

;;; Convenience function to dump docs
(defun dump-docs ()
  "Dump all documentation to stdout in markdown format."
  (render-all-docs-md))

;;; ------------------------------------------------------------------------
;;; LLMS.TXT dense index (issue: docs/llms-txt)
;;;
;;; One line per HELP-DB entry: `NAME (TYPE) SYNTAX -- DESCRIPTION`, grouped
;;; under a `## category` heading, categories and entries both alphabetized
;;; for a stable diff across regenerations. Any HELP-DB entry that no
;;; category claims (checked at generation time -- see the OTHER bucket
;;; below) still gets a line, so this never silently drops a documented
;;; symbol the way scraping generated-reference.md by hand would.
;;; scripts/generate-llms-txt.sh calls this via `-s "(render-llms-index)"`
;;; and splices the output into the llms.txt template.

(defun llms-index-truncate (s limit)
  "Cap string S to LIMIT chars, appending ... when truncated."
  (if (and s (> (length s) limit))
      (concat (substring s 0 (- limit 3)) "...")
      s))

(defun llms-index-one-line (s)
  "Collapse embedded newlines/tabs to single spaces so a HELP-DB
description prints on exactly one output line."
  (if s
      (string-replace-all (string-replace-all s "\n" " ") "\t" " ")
      s))

(defun llms-index-type-tag (type)
  "Abbreviate a HELP-DB TYPE symbol to a short bracketed tag."
  (cond
    ((eq type 'FUNCTION) "[f]")
    ((eq type 'MACRO) "[m]")
    ((eq type 'SPECIAL-FORM) "[s]")
    ((eq type 'VARIABLE) "[v]")
    (t (concat "[" (prin1-to-string type) "]"))))

(defun llms-index-line (name)
  "Print one dense reference line for NAME's HELP-DB entry."
  (let ((entry (get-doc name)))
    (if entry
        (let ((type (doc-get entry 'TYPE))
              (syntax (doc-get entry 'SYNTAX))
              (desc (doc-get entry 'DESCRIPTION)))
          (progn
            (princ (prin1-to-string name))
            (princ " ")
            (princ (llms-index-type-tag type))
            (if syntax
                (progn
                  (princ " ")
                  (princ (llms-index-one-line syntax)))
                nil)
            (if desc
                (progn
                  (princ " -- ")
                  (princ (llms-index-truncate (llms-index-one-line desc) 110)))
                nil)
            (terpri)))
        nil)))

(defun llms-index-sorted-syms (syms)
  "Alphabetize SYMS by printed name for stable output."
  (sort syms
        (lambda (a b)
          (string-lessp (prin1-to-string a) (prin1-to-string b)))))

(defun llms-index-category (cat)
  "Print a `## name -- description` heading, then one line per symbol."
  (progn
    (princ "## ")
    (princ (car cat))
    (princ " -- ")
    (princ (cadr cat))
    (terpri)
    (mapcar #'llms-index-line (llms-index-sorted-syms (caddr cat)))
    (terpri)))

(defun render-llms-index ()
  "Dense, one-line-per-function reference of the whole HELP-DB, grouped by
category, alphabetized. Used to generate the function-index section of
llms.txt -- see scripts/generate-llms-txt.sh."
  (let* ((cats (sort (list-categories)
                      (lambda (a b)
                        (string-lessp (prin1-to-string (car a))
                                      (prin1-to-string (car b))))))
         (categorized nil))
    (progn
      (mapcar (lambda (c) (setq categorized (append categorized (caddr c))))
              cats)
      (mapcar #'llms-index-category cats)
      (let ((other (set-difference (keys HELP-DB) categorized)))
        (if other
            (llms-index-category (list 'other "Uncategorized" other))
            nil)))))

;;; REQUIRE-ABLE (issue #256): `(require 'doc-renderer)` on a with_prelude()
;;; environment loads exactly this file. with_stdlib() still loads it
;;; unconditionally, unchanged. Its functions read the help database
;;; (lib/98-help-system.lisp / lib/99-help-data.lisp) at call time, not at
;;; load time, so it does not itself REQUIRE them -- require those yourself
;;; before calling DUMP-DOCS/RENDER-ALL-DOCS-MD if the database is empty.
;;; Registered as a module for introspection (issue #56). The markdown
;;; renderers stay FLAT (they compose with the flat help database and
;;; register-doc surface); this DEFMODULE only records metadata -- no
;;; with-module body rewrite, nothing imported.
(require 'modules)
(defmodule doc-renderer
  (:export render-markdown-header render-markdown-code render-doc-entry-md
           render-category-md render-all-docs-md render-function-index-md
           dump-docs render-llms-index))
(provide 'doc-renderer)
